In [1]:
import pandas as pd

In [2]:
table = pd.read_csv("/content/May_5_results_query_disease.csv")
table

,Unnamed: 0,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,...,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID,Pathologization category
0,0,Daniel E.; Gulati A.; Saxena S.; Urgun D.A.; B...,"Daniel, Ebenezer (56405131200); Gulati, Anjali...",56405131200; 59940730100; 59940973200; 5721620...,GM-VGG-Net: A Gray Matter-Based Deep Learning ...,2025,Diagnostics,15,11,1425,...,NaN,NaN,English,Diagn.,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105007938314,Keyword
1,1,Prabha K V.R.; Bindu C.H.; Devi K.R.,"Prabha K, Venkata Ratna (60560646000); Bindu, ...",60560646000; 57212328725; 57190968820,Spatio-Graphical Vision Transformer Framework ...,2025,Proceedings of 5th International Conference on...,NaN,NaN,NaN,...,NaN,NaN,English,Proc. Int. Conf. Ubiquitous Comput. Intel. Inf...,Conference paper,Final,NaN,Scopus,2-s2.0-105034839526,Keyword
2,2,Lawan A.A.; Abdullahi H.Z.; Abdullahi A.Y.; Ta...,"Lawan, Abdulmalik Ahmad (57193170933); Abdulla...",57193170933; 60075020200; 60074694100; 5722310...,A Systematic Literature Review on the Applicat...,2025,OBM Neurobiology,9,3,298,...,NaN,NaN,English,OBM. Neurobiol.,Review,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105014373089,Unrelated
3,3,Jahani A.; Jahani I.; Khadem A.; Braden B.B.; ...,"Jahani, Ali (60076608300); Jahani, Iman (59306...",60076608300; 59306808000; 57027659100; 2302436...,Twinned neuroimaging analysis contributes to i...,2024,Scientific Reports,14,1,20120,...,NaN,39209988.0,English,Sci. Rep.,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85202668189,Keyword
4,4,Rakshe C.; Kunneth S.; Sundaram S.; Murugappan...,"Rakshe, Chetan (58477522500); Kunneth, Suja (5...",58477522500; 58477675000; 7101967314; 25825367...,Autism spectrum disorder diagnosis using fract...,2024,Neural Computing and Applications,36,20,NaN,...,NaN,NaN,English,Neural Comput. Appl.,Article,Final,NaN,Scopus,2-s2.0-85191100810,Unrelated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,61,Mostafa S.; Tang L.; Wu F.-X.,"Mostafa, Sakib (57212683440); Tang, Lingkai (5...",57212683440; 57193355455; 55843631800,Diagnosis of Autism Spectrum Disorder Based on...,2019,IEEE Access,7,NaN,8827515,...,NaN,NaN,English,IEEE Access,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85078238274,Refers to autism as a disease
262,62,Anirudh R.; Thiagarajan J.J.,"Anirudh, Rushil (55603055100); Thiagarajan, Ja...",55603055100; 25929725600,Machine learning methods for autism spectrum d...,2021,Neural Engineering Techniques for Autism Spect...,NaN,NaN,NaN,...,NaN,NaN,English,Neural Engineering Techniques for Autism Spect...,Book chapter,Final,NaN,Scopus,2-s2.0-85129012898,Refers to autism as a disease
263,63,Leming M.; Suckling J.,"Leming, Matthew (57203919652); Suckling, John ...",57203919652; 7004124496,Deep Learning on Brain Images in Autism: What ...,2019,Lecture Notes in Computer Science (including s...,11486 LNCS,NaN,NaN,...,NaN,NaN,English,Lect. Notes Comput. Sci.,Conference paper,Final,NaN,Scopus,2-s2.0-85065879641,Keyword
264,64,Smith R.X.; Jann K.; Dapretto M.; Wang D.J.J.,"Smith, Robert X. (55792753400); Jann, Kay (243...",55792753400; 24398746500; 6602424457; 57219569726,Imbalance of functional connectivity and tempo...,2018,Frontiers in Neuroscience,12,NOV,869,...,NaN,NaN,English,Front. Neurosci.,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85057719452,Unrelated
265,65,Kazeminejad A.; Sotero R.C.,"Kazeminejad, Amirali (57203224961); Sotero, Ro...",57203224961; 15846936500,The Importance of Anti-correlations in Graph T...,2020,Frontiers in Neuroscience,14,NaN,676,...,NaN,NaN,English,Front. Neurosci.,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85089805822,Refers to autism as a disease

In [3]:
table["Pathologization category"].value_counts()

Pathologization category
Refers to autism as a disease    160
Keyword                           57
Unrelated                         28
No data                           21
Name: count, dtype: int64

In [4]:
table_disease = table[table["Pathologization category"] == "Refers to autism as a disease"]
table_disease

,Unnamed: 0,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,...,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID,Pathologization category
8,8,Zhang Y.; Fang Y.; Yu X.; Peng Y.; Ju Z.,"Zhang, Yihang (59378063400); Fang, Yinfeng (55...",59378063400; 55869810300; 57984159500; 5664721...,Cosine Similarity Graph Attention Networks for...,2024,2024 International Convention on Rehabilitatio...,NaN,NaN,NaN,...,NaN,NaN,English,Int. Conv. Rehabil. Eng. Assist. Technol. Worl...,Conference paper,Final,NaN,Scopus,2-s2.0-85207045560,Refers to autism as a disease
11,11,Zeng W.; Yin F.; Song P.; Wu Y.; Zhao C.; Wu G...,"Zeng, Wenwen (57911599800); Yin, Feiyu (572167...",57911599800; 57216781063; 59928338300; 5815109...,Adaptive Multi-Scale Dynamic Graph Representat...,2025,IEEE Journal of Biomedical and Health Informatics,29,12,NaN,...,ITIBF,41359708.0,English,IEEE J. Biomedical Health Informat.,Article,Final,NaN,Scopus,2-s2.0-105024145724,Refers to autism as a disease
13,13,Ahmed M.; Hussain S.; Ali F.; Gárate-Escamilla...,"Ahmed, Masroor (57224704037); Hussain, Sadam (...",57224704037; 58598677700; 60017822800; 5877180...,Summarizing Recent Developments on Autism Spec...,2025,Applied Sciences (Switzerland),15,14,8056,...,NaN,NaN,English,Appl. Sci.,Review,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105011866507,Refers to autism as a disease
14,14,Manoj G.; Gupta V.; Bhattacharya A.; Aleem S.G...,"Manoj, Gokul (58022012500); Gupta, Vaibhavi (5...",58022012500; 58023302400; 58023091700; 5895427...,Diagnostic classification of autism spectrum d...,2025,Multimedia Tools and Applications,84,8,NaN,...,MTAPF,NaN,English,Multimedia Tools Appl,Article,Final,NaN,Scopus,2-s2.0-105001076505,Refers to autism as a disease
16,16,Ali S.; Baloch Z.; Narejo S.; Shaikh A.M.,"Ali, Sumera (60140751500); Baloch, Zartasha (5...",60140751500; 57195249108; 57191502651; 6013961...,"A Review of Developments in Generative AI, Mac...",2025,VFAST Transactions on Software Engineering,13,2,NaN,...,NaN,NaN,English,VFAST trans. softw. eng.,Review,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105018784930,Refers to autism as a disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,58,Akhavan Aghdam M.; Sharifi A.; Pedram M.M.,"Akhavan Aghdam, Maryam (57201942222); Sharifi,...",57201942222; 24725517500; 55389555600,Combination of rs-fMRI and sMRI Data to Discri...,2018,Journal of Digital Imaging,31,6,NaN,...,JDIME,29736781.0,English,J. Digit. Imaging,Article,Final,All Open Access; Bronze Open Access,Scopus,2-s2.0-85046545759,Refers to autism as a disease
260,60,Liang Y.; Liu B.; Zhang H.,"Liang, Yin (57193761102); Liu, Baolin (5572071...",57193761102; 55720716800; 57311283400,A Convolutional Neural Network Combined With P...,2021,IEEE Transactions on Neural Systems and Rehabi...,29,NaN,NaN,...,ITNSB,34648452.0,English,IEEE Trans. Neural Syst. Rehabil. Eng.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85117746623,Refers to autism as a disease
261,61,Mostafa S.; Tang L.; Wu F.-X.,"Mostafa, Sakib (57212683440); Tang, Lingkai (5...",57212683440; 57193355455; 55843631800,Diagnosis of Autism Spectrum Disorder Based on...,2019,IEEE Access,7,NaN,8827515,...,NaN,NaN,English,IEEE Access,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85078238274,Refers to autism as a disease
262,62,Anirudh R.; Thiagarajan J.J.,"Anirudh, Rushil (55603055100); Thiagarajan, Ja...",55603055100; 25929725600,Machine learning methods for autism spectrum d...,2021,Neural Engineering Techniques for Autism Spect...,NaN,NaN,NaN,...,NaN,NaN,English,Neural Engineering Techniques for Autism Spect...,Book chapter,Final,NaN,Scopus,2-s2.0-85129012898,Refers to autism as a disease
265,65,Kazeminejad A.; Sotero R.C.,"Kazeminejad, Amirali (57203224961); Sotero, Ro...",57203224961; 15846936500,The Importance of Anti-correlations in Graph T...,2020,Frontiers in Neuroscience,14,NaN,676,...,NaN,NaN,English,Front. Neurosci.,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-85089805822,Refers to autism as a disease

In [5]:
table_disease.to_csv("table_explicit_pathologization.csv")

In [6]:
pd.set_option('display.max_rows', None)

# Publication source name

In [7]:
table_disease["Source title"].value_counts()

Source title
Frontiers in Neuroscience                                                                                                                                  10
Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)                        7
Biomedical Signal Processing and Control                                                                                                                    7
Communications in Computer and Information Science                                                                                                          6
Computers in Biology and Medicine                                                                                                                           5
Frontiers in Human Neuroscience                                                                                                                             4
IEEE Transactions on Neural Systems and Rehabilitation Engineering                                                                                          3
ACM International Conference Proceeding Series                                                                                                              3
Applied Sciences (Switzerland)                                                                                                                              3
Cerebral Cortex                                                                                                                                             3
IEEE Journal of Biomedical and Health Informatics                                                                                                           2
Brain Sciences                                                                                                                                              2
Brain Informatics                                                                                                                                           2
Artificial Intelligence in Medicine                                                                                                                         2
Proceedings of the Annual International Conference of the IEEE Engineering in Medicine and Biology Society, EMBS                                            2
Translational Psychiatry                                                                                                                                    2
IEEE Access                                                                                                                                                 2
Medical and Biological Engineering and Computing                                                                                                            2
Behavioural Brain Research                                                                                                                                  2
SN Computer Science                                                                                                                                         2
Reviews in the Neurosciences                                                                                                                                2
NeuroImage                                                                                                                                                  2
Journal of Neuroscience Methods                                                                                                                             2
Nature Communications                                                                                                                                       2
Frontiers in Psychiatry                                                                                                                                     2
NeuroImage: Clinical                                                                                                                                        2
Journal of Digital Imaging                                                                                                                                  2
IEEE Transactions on Medical Imaging                                                                                                                        1
Lecture Notes in Computer Science                                                                                                                           1
Future of AI in Medical Imaging                                                                                                                             1
Arabian Journal for Science and Engineering                                                                                                                 1
IEEE Region 10 Annual International Conference, Proceedings/TENCON                                                                                          1
Multimedia Tools and Applications                                                                                                                           1
2024 International Convention on Rehabilitation Engineering and Assistive Technology and World Rehabilitation Robot Convention, WRRC 2024 - Proceedings     1
Journal of Medical Systems                                                                                                                                  1
VFAST Transactions on Software Engineering                                                                                                                  1
Neural Networks                                                                                                                                             1
Heliyon                                                                                                                                                     1
Proceedings - 2024 IEEE International Conference on Bioinformatics and Biomedicine, BIBM 2024                                                               1
IEEE Transactions on Consumer Electronics                                                                                                                   1
ICCPR 2024 - Proceedings of the 2024 13th International Conference on Computing and Pattern Recognition                                                     1
Scientific Reports                                                                                                                                          1
Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)                        1
Journal of Technology in Behavioral Science                                                                                                                 1
GigaScience                                                                                                                                                 1
Proceedings of the International Conference on Intelligent Computing and Control Systems, ICICCS 2025                                                       1
Information Technology and Control                                                                                                                          1
International Journal of Imaging Systems and Technology                                                                                                     1
Big Data Mining and Analytics                                                                                                                               1
Proceedings of IEEE InC4 2023 - 2023 IEEE International Conference on Contemporary Computing and Communications                                             1
Proceedings - International Research Conference on Smart Computing and Systems Engineering, SCSE 2021                                                       1
2025 4th OPJU International Technology Conference on Smart Computing for Innovation and Advancement in Industry 5.0, OTCON 2025                             1
Current Neuropharmacology                                                                                                                                   1
npj Mental Health Research                                                                                                                                  1
Proceedings of the International Joint Conference on Neural Networks                                                                                        1
BMC Bioinformatics                                                                                                                                          1
Applied Soft Computing                                                                                                                                      1
IEEE International Conference on Electrical, Electronics, Communication and Computers, ELEXCOM 2023                                                         1
Proceedings - International Conference on Image Processing, ICIP                                                                                            1
Brain Research                                                                                                                                              1
Neural Engineering Techniques for Autism Spectrum Disorder: Volume 2: Diagnosis and Clinical Analysis                                                       1
Diagnostics                                                                                                                                                 1
Psychiatry Research - Neuroimaging                                                                                                                          1
Proceedings of SPIE - The International Society for Optical Engineering                                                                                     1
International Journal of Neural Systems                                                                                                                     1
Frontiers in Neuroinformatics                                                                                                                               1
International Journal of Biomedical Imaging                                                                                                                 1
Proceedings of the 9th International Conference on Inventive Systems and Control, ICISC 2025                                                                1
Cognitive Neurodynamics                                                                                                                                     1
Computerized Medical Imaging and Graphics                                                                                                                   1
JAMA Psychiatry                                                                                                                                             1
Neuropsychologia                                                                                                                                            1
Jisuanji Gongcheng/Computer Engineering                                                                                                                     1
2023 1st International Conference on Health Science and Technology, ICHST 2023                                                                              1
Medical Image Analysis                                                                                                                                      1
Neural Computing and Applications                                                                                                                           1
Molecular Psychiatry                                                                                                                                        1
Proceedings - International Symposium on Biomedical Imaging                                                                                                 1
ICARC 2022 - 2nd International Conference on Advanced Research in Computing: Towards a Digitally Empowered Society                                          1
Progress in Biomedical Optics and Imaging - Proceedings of SPIE                                                                                             1
2022 6th International Conference on Trends in Electronics and Informatics, ICOEI 2022 - Proceedings                                                        1
Progress in Molecular Biology and Translational Science                                                                                                     1
Proceedings - 2023 5th International Conference on Intelligent Medicine and Image Processing, IMIP 2023                                                     1
NILES 2024 - 6th Novel Intelligent and Leading Emerging Sciences Conference, Proceedings                                                                    1
2022 7th International Conference on Signal and Image Processing, ICSIP 2022                                                                                1
Journal of Computational Biology                                                                                                                            1
PLoS ONE                                                                                                                                                    1
Frontiers in Genetics                                                                                                                                       1
American Journal of Psychiatry                                                                                                                              1
Sensors (Switzerland)                                                                                                                                       1
Progress in Neuro-Psychopharmacology and Biological Psychiatry                                                                                              1
Cortex                                                                                                                                                      1
Symmetry                                                                                                                                                    1
9th International Symposium on Telecommunication: With Emphasis on Information and Communication Technology, IST 2018                                       1
Nature Neuroscience                                                                                                                                         1
Proceedings - 2021 14th International Congress on Image and Signal Processing, BioMedical Engineering and Informatics, CISP-BMEI 2021                       1
Frontiers in Computational Neuroscience                                                                                                                     1
Journal of Imaging                                                                                                                                          1
Review Journal of Autism and Developmental Disorders                                                                                                        1
Proceedings of Machine Learning Research                                                                                                                    1
2020 11th International Conference on Computing, Communication and Networking Technologies, ICCCNT 2020                                                     1
Neural Engineering Techniques for Autism Spectrum Disorder: Volume 1: Imaging and Signal Analysis                                                           1
Name: count, dtype: int64

# Year

In [8]:
table_disease["Year"].value_counts()

Year
2025    29
2023    28
2024    25
2021    21
2022    21
2020    16
2019     7
2018     6
2016     3
2017     3
2015     1
Name: count, dtype: int64

# Funding source

In [9]:
funding_sources = []

for _, row in table_disease.iterrows():
  list_sources = (str(row["Funding Details"])).split("; ")
  funding_sources = funding_sources + list_sources

split_comma = []

for source in funding_sources:
  split_comma = split_comma + source.split(", ")

# Many strings that will appear in the list are just the acronym of the funding sponsor or the grant number
split_comma

['National Key Research and Development Program of China',
 'NKRDPC',
 '(2023YFE0114900)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 'Basic Public Welfare Research Program of Zhejiang Province',
 '(NO.LQ20F020016)',
 'Basic Public Welfare Research Program of Zhejiang Province',
 'Fudan University FudanX24AI038',
 'National Natural Science Foundation of China',
 'NSFC',
 '(82372096AI)',
 'nan',
 'Indian Institute of Technology',
 'Banaras Hindu University',
 'BHU',
 'nan',
 'nan',
 'National Natural Science Foundation of China',
 'NSFC',
 '(61773006)',
 'National Natural Science Foundation of China',
 'NSFC',
 'Medical-Industrial Intersection Joint Foundation of Liaoning Province',
 '(2022-YGJC-14)',
 'National Science Foundation',
 'NSF',
 'Air Force Office of Scientific Research',
 'AFOSR',
 'International Business Machines Corporation',
 'IBM',
 'Japan Society for the Promotion of Science',
 'JSPS',
 'Shenzhen Key Laboratory of Intelligent Bioinformatics',
 '(ZDSYS2022042210 3800001)',
 'Science',
 'Technology and Innovation Commission of Shenzhen Municipality',
 '(KQTD20200820113106007',
 'SGDX20201103095603009)',
 'National Natural Science Foundation of China',
 'NSFC',
 '(62272449',
 'U22A2041)',
 'Youth Innovation Promotion Association',
 'YIPA',
 '(Y2021101)',
 'Chinese Academy of Sciences',
 'CAS',
 '(XDB38050100)',
 'Shenzhen Basic Research Fund',
 '(RCYX20200714114734194)',
 'Special Project for Research and Development in Key areas of Guangdong Province',
 '(2021B0101310002)',
 'Institute for Information and Communications Technology Promotion',
 'IITP',
 'National Research Foundation of Korea',
 'NRF',
 '(2022R1A4A1033856)',
 'MSIT',
 '(2022-0-00959)',
 'Artificial Intelligence Graduate School Program',
 'Korea University',
 '(2019-0-00079)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 '(2022YFA1603602)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 'National Natural Science Foundation of China',
 'NNSFC',
 '(82272070',
 'W2432042',
 '62301344)',
 'National Natural Science Foundation of China',
 'NNSFC',
 'IHM',
 '(2023IHM01094)',
 'Qinglan Project of Jiangsu Province of China',
 'National Natural Science Foundation of China',
 'NSFC',
 '(51877013)',
 'National Natural Science Foundation of China',
 'NSFC',
 'nan',
 'Science and Engineering Research Board',
 'SERB',
 'Anusandhan National Research Foundation',
 'Department of Science and Technology',
 'Ministry of Science and Technology',
 'India',
 'DST',
 '(SRG/2022/001920',
 '30.11.2022)',
 'Department of Science and Technology',
 'Ministry of Science and Technology',
 'India',
 'DST',
 'National Natural Science Foundation of China',
 'NSFC',
 '(62076209',
 'W2411084)',
 'National Natural Science Foundation of China',
 'NSFC',
 'Science and Engineering Research Board',
 'SERB',
 '(SRG/2021/002289)',
 'Science and Engineering Research Board',
 'SERB',
 'Science and Engineering Research Board',
 'SERB',
 'Department of Science and Technology',
 'Ministry of Science and Technology',
 'India',
 'IndiaDST',
 '(SRG/2022/001920',
 '30.11.2022)',
 'Department of Science and Technology',
 'Ministry of Science and Technology',
 'India',
 'IndiaDST',
 'nan',
 'nan',
 'nan',
 'nan',
 'Natural Science Foundation of Shandong Province',
 '(ZR2020MF041',
 'ZR2022MF237)',
 'Natural Science Foundation of Shandong Province',
 'nan',
 'Natural Science Foundation of Shandong Province',
 '(ZR2022MF237',
 'ZR2020MF041)',
 'Natural Science Foundation of Shandong Province',
 'Artificial Intelligence Convergence Innovation Human Resources Development',
 'Artificial Intelligence Innovation Hub',
 'Institute for Information and Communications Technology Planning and Evaluation',
 'Inha University',
 'Inha',
 '(2021–0-02068)',
 'Inha University',
 'Inha',
 'Ministry of Science',
 'ICT and Future Planning',
 'MSIP',
 '(2022–0-00448',
 'RS-2022–00155915)',
 'Ministry of Science',
 'ICT and Future Planning',
 'MSIP',
 'National Research Foundation of Korea',
 'NRF',
 '(NRF-2021R1F1A1052303',
 'NRF-2022R1A5A7033499)',
 'National Research Foundation of Korea',
 'NRF',
 'Institute for Information and Communications Technology Promotion',
 'IITP',
 'Institute for Basic Science',
 'IBS',
 '(IBS-R015-D1)',
 'Institute for Basic Science',
 'IBS',
 'National Institutes of Health',
 'NIH',
 '(R01DA040487)',
 'National Institutes of Health',
 'NIH',
 'National Science Foundation',
 'NSF',
 '(2112455',
 '2R01EB006841)',
 'National Science Foundation',
 'NSF',
 'nan',
 'nan',
 'nan',
 'National Natural Science Foundation of China',
 'NNSF',
 '(62172139)',
 'Hebei Province Science and Technology Support Program',
 '(246Z0104G)',
 'Shijiazhuang Key Research and Development Special Project for Universities in Hebei Province',
 '(2511300801A)',
 'Hebei University',
 '(IT2023B05)',
 'Deanship of Scientific Research',
 'Prince Sattam bin Abdulaziz University',
 'DSR',
 'King Abdulaziz University',
 'KAU',
 'Ministry of Education – Kingdom of Saudi Arabi',
 'MOE',
 'Institutional Fund Projects',
 '(878-612-1443)',
 'Institut de Valorisation des Données',
 'IVADO',
 'Santé',
 'SciChefQC',
 'Canadian Open Neuroscience Platform',
 'CONP',
 'Courtouis Neuromod Foundation',
 'Consortium canadien en neurodégénérescence associée au vieillissement',
 'CCNA',
 'Centre de recherche de l’Institut universitaire de geriatrie de Montreal',
 'Azrieli Foundation',
 '(3388)',
 'Azrieli Foundation',
 'Australian Research Council',
 'ARC',
 '(DE170101134',
 'DP180101192)',
 'Australian Research Council',
 'ARC',
 'Shanghai Key Laboratory Open Project',
 'National Key Research and Development Program of China',
 'NKRDPC',
 '(2022ZD0160703)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 'Science and Technology Program of Zhejiang Province',
 '(2022C03134)',
 'Science and Technology Program of Zhejiang Province',
 'Natural Science Foundation of Shandong Province',
 '(ZR2021MH227)',
 'Natural Science Foundation of Shandong Province',
 'Science and Technology Commission of Shanghai Municipality',
 'STCSM',
 '(22DZ2229005)',
 'Science and Technology Commission of Shanghai Municipality',
 'STCSM',
 'National Natural Science Foundation of China',
 'NSFC',
 '(62202422)',
 'National Natural Science Foundation of China',
 'NSFC',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'Natural Science Foundation of Xinjiang Uygur Autonomous Region',
 '(2022D01C692)',
 'Natural Science Foundation of Xinjiang Uygur Autonomous Region',
 'Central South University Innovation-Driven Research Programme',
 '(2023CXQD018)',
 'Basic Research Foundation of Universities in the Xinjiang Uyghur Autonomous Region of China',
 '(XJEDU2023P012)',
 'National Natural Science Foundation of China',
 'NSFC',
 '(62266043)',
 'National Natural Science Foundation of China',
 'NSFC',
 'Key Research and Development Project in Xinjiang Uyghur Autonomous Region',
 '(2022B01006)',
 'Tianshan Innovation Team Program of Xinjiang Uyghur Autonomous Region of China',
 '(2023D14012)',
 'Outstanding Young Talent Foundation of Xinjiang Uyghur Autonomous Region of China',
 '(2023TSYCCX0043)',
 'Natural Science Foundation of Hunan Province',
 '(2022JJ30753)',
 'Natural Science Foundation of Hunan Province',
 'Finance science and technology project of Xinjiang Uyghur Autonomous Region',
 '(2023B01029-1,2023B01029-2)',
 'Excellent Youth Foundation of Xinjiang Uyghur Autonomous Region of China',
 '(2023D01E01)',
 'Science and Technology Plan Project of University of Jinan',
 '(XKY2078)',
 'University of Jinan',
 'UJN',
 '(J2158)',
 'University of Jinan',
 'UJN',
 'ABIDE',
 'Prince Sultan University',
 'PSU',
 '1000 Health Research',
 'Artificial Intelligence in Medicine',
 'Centro Nazionale di Ricerca',
 'FAIR',
 'FAIR-AIM',
 'PNRR',
 'Tuscany Government',
 '(POR FSE 2014–2020)',
 'European Commission',
 'EC',
 'Ministero della Salute',
 'Key Project of Independent Innovation Research Fund',
 'Huazhong University of Science and Technology',
 'HUST',
 '(2017KFYXJJ100>)',
 'Huazhong University of Science and Technology',
 'HUST',
 'Tongji Hospital',
 'TJH',
 '(2023B14',
 '2023B33>)',
 'Tongji Hospital',
 'TJH',
 'Natural Science Foundation of Zhejiang Province',
 'ZJNSF',
 '(LD21F020001',
 'Z20F020022)',
 'Natural Science Foundation of Zhejiang Province',
 'ZJNSF',
 'National Natural Science Foundation of China',
 'NSFC',
 '(62072340)',
 'National Natural Science Foundation of China',
 'NSFC',
 'Natural Science Foundation of Yangzhou Municipality',
 '(ZS2022001)',
 'Natural Science Foundation of Yangzhou Municipality',
 'Natural Science Foundation of Shandong Province',
 '(ZR2021MH227)',
 'Natural Science Foundation of Shandong Province',
 'National Natural Science Foundation of China',
 'NNSF',
 '(62071330)',
 'National Natural Science Foundation of China',
 'NNSF',
 'Jinan Science and Technology Bureau',
 '(202019181)',
 'Jinan Science and Technology Bureau',
 'nan',
 'National Natural Science Foundation of China',
 'NSFC',
 'Changsha City Natural Science Foundation of China',
 '(kq2208103)',
 'Hunan Provincial Natural Science Foundation of China',
 '(2023JJ40362)',
 'Hunan Health and Health Commission',
 '(C2019039)',
 'nan',
 'National Natural Science Foundation of China',
 'NSFC',
 '(62002269)',
 'National Natural Science Foundation of China',
 'NSFC',
 'Science and Engineering Research Board',
 'SERB',
 'Department of Science and Technology',
 'Ministry of Science and Technology',
 'India',
 'DST',
 '(SRG/2022/001920',
 '30.11.2022)',
 'Sichuan Province Science and Technology Support Program',
 '(2019YJ0193',
 '2021YFG0002',
 '2021YFG0126',
 '2022YFS0180)',
 'Sichuan Province Science and Technology Support Program',
 'National Natural Science Foundation of China',
 'NSFC',
 '(61701078',
 '62006038',
 '62276049)',
 'National Natural Science Foundation of China',
 'NSFC',
 'University of Electronic Science and Technology of China',
 'UESTC',
 '(ZYGX2021YGLH014)',
 'University of Electronic Science and Technology of China',
 'UESTC',
 'National Key Research and Development Program of China',
 'NKRDPC',
 '(2023YFE0118600)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 'nan',
 'Scientific and Technological Innovation Foundation of Shunde Graduate School of University of Science and Technology Beijing',
 '(BK19CE017',
 'BK20AE004)',
 'National Natural Science Foundation of China',
 'NSFC',
 '(12071025)',
 'National Natural Science Foundation of China',
 'NSFC',
 'nan',
 'nan',
 'Horizon 2020 Framework Programme',
 'H2020',
 'H2020 Marie Skłodowska-Curie Actions',
 'MSCA',
 '(777720)',
 'H2020 Marie Skłodowska-Curie Actions',
 'MSCA',
 'Ministerio de Economía y Competitividad',
 'MINECO',
 '(TIN2017-85827-P)',
 'Ministerio de Economía y Competitividad',
 'MINECO',
 'European Regional Development Fund',
 'ERDF',
 'nan',
 'National Natural Science Foundation of China',
 'NSFC',
 '(81771876)',
 'National Natural Science Foundation of China',
 'NSFC',
 'National Key Research and Development Program of China',
 'NKRDPC',
 '(2016YFC1401900)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 'nan',
 'Key Special Projects of Health and Family Planning Science and Technology in Zhenjiang City',
 '(SHW2017019)',
 'National Natural Science Foundation of China',
 'NSFC',
 '(61572239',
 '61772242',
 '61976106)',
 'China Postdoctoral Science Foundation',
 '(2017M611737)',
 'Six Talent Peaks Project in Jiangsu Province',
 '(DZXX-122)',
 'National Natural Science Foundation of China',
 'NSFC',
 '(12071025)',
 'Basic and Applied Basic Research Foundation of Guangdong Province',
 '(2022A1515011172)',
 'Fundação para a Ciência e a Tecnologia',
 'FCT',
 '(Incentivo/SAU/LA0001/2013)',
 'International Institute of Information Technology',
 'Hyderabad',
 'IIITH',
 'nan',
 'Ministry of Science',
 'ICT and Future Planning',
 'MSIP',
 '(2020M3E5D9080788)',
 'Ministry of Science',
 'ICT and Future Planning',
 'MSIP',
 'National Research Foundation of Korea',
 'NRF',
 '(2019M3E5D1A01069345',
 'NRF-2020-R1F1A1048529)',
 'National Research Foundation of Korea',
 'NRF',
 'National Natural Science Foundation of China',
 'NSFC',
 '(82001898)',
 'National Natural Science Foundation of China',
 'NSFC',
 'nan',
 'Artificial Intelligence in Medicine: next steps',
 'Partenariato Esteso PE00000013 FAIR',
 'European Commission',
 'EC',
 'Instituto Nazionale di Fisica Nucleare',
 'INFN',
 'nan',
 'Sichuan Province Science and Technology Support Program',
 '(2019YJ0193',
 '2021YFG0126',
 '2021YFG0366',
 '2022YFS0180)',
 'Sichuan Province Science and Technology Support Program',
 'National Natural Science Foundation of China',
 'NSFC',
 '(61701078',
 '61720106004',
 '61872068',
 '62006038',
 '62276049)',
 'National Natural Science Foundation of China',
 'NSFC',
 'University of Electronic Science and Technology of China',
 'UESTC',
 '(ZYGX2021YGLH014)',
 'University of Electronic Science and Technology of China',
 'UESTC',
 'nan',
 'nan',
 'Tian Jiabing Scholar Plan in Shaanxi normal university',
 'National Natural Science Foundation of China',
 'NSFC',
 '(11974231',
 '12275165',
 '42271315',
 '61936007',
 '61976131)',
 'National Natural Science Foundation of China',
 'NSFC',
 'Fundamental Research Funds for the Central Universities',
 '(GK202202003',
 'GK202204003)',
 'Fundamental Research Funds for the Central Universities',
 'Michael P. Milham',
 'National Institute of Mental Health',
 'NIMH',
 '(K23MH087770)',
 'National Institute of Mental Health',
 'NIMH',
 'Leon Levy Foundation',
 'Åke Wiberg Stiftelse',
 '(M22-0088)',
 'Åke Wiberg Stiftelse',
 'ITEA',
 'Child Mind Institute',
 'CMI',
 '(R03MH096321)',
 'Child Mind Institute',
 'CMI',
 'VINNOVA',
 '(2021-01954)',
 'VINNOVA',
 'Stavros Niarchos Foundation',
 'SNF',
 'Vetenskapsrådet',
 'VR',
 '(2017-04889)',
 'Vetenskapsrådet',
 'VR',
 'National Natural Science Foundation of China',
 'NSFC',
 '(62027827',
 '62106032)',
 'National Natural Science Foundation of China',
 'NSFC',
 'China Postdoctoral Science Foundation',
 '(2022MD713691)',
 'China Postdoctoral Science Foundation',
 'Chongqing University of Posts and Telecommunications',
 'CUPT',
 '(A2023-01)',
 'Chongqing University of Posts and Telecommunications',
 'CUPT',
 'Natural Science Foundation of Chongqing',
 '(cstc2019jcyj-cxttX0002',
 'cstc2020jcyjzdxmX0025)',
 'Natural Science Foundation of Chongqing',
 'Chongqing Municipal Education Commission',
 'CQMEC',
 '(HZ2021008)',
 'Chongqing Municipal Education Commission',
 'CQMEC',
 'Chongqing Postdoctoral Science Special Foundation',
 '(2021XM3028)',
 'Chongqing Postdoctoral Science Special Foundation',
 'National Key Research and Development Program of China',
 'NKRDPC',
 '(2021YFF0704100)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 'Artificial Intelligence in Medicine: next steps',
 'INFN-CSN5',
 'Ministero della Salute',
 '(AIMS-2-Trials)',
 'Instituto Nazionale di Fisica Nucleare',
 'INFN',
 'Science Project of Liaoning Provice in China',
 '(2021-MS-105)',
 'National Natural Science Foundation of China',
 'NSFC',
 '(059',
 '62\u2009076\u2009059)',
 'National Natural Science Foundation of China',
 'NSFC',
 'National Natural Science Foundation of China',
 'NSFC',
 '(61976248',
 '62036013',
 '81301199',
 '81901698)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 '(2016YFC1307100',
 '2017YFC0107400)',
 'Key Science and Technology Program of Shaanxi Province',
 '(2017ZDXM-SF-047)',
 'Science Project of Liaoning Province',
 '(2021-MS-105)',
 'National Natural Science Foundation of China',
 'NNSFC',
 'NNSF',
 'NSF',
 'NSFC',
 '(62076059)',
 'National Natural Science Foundation of China',
 'NNSFC',
 'NNSF',
 'NSF',
 'NSFC',
 'Autonomous Government of Andalusia (Spain)',
 '(UMA20-FEDERJA-108)',
 'Universidad de Málaga',
 'UMA',
 '(B1-2019 01',
 'B1-2019 02)',
 'Instituto de Salud Carlos III',
 'ISCIII',
 '(IFI19/00009)',
 'European Regional Development Fund',
 'ERDF',
 'First Affiliated Hospital of Soochow University',
 'Natural Science Foundation of Bo Xi',
 '(BXQN202118)',
 'Hainan Key Research and Development Plan for Scientific and Technological Collaboration Projects',
 '(GHYF2022015)',
 'nan',
 'Swiss Data Science Center',
 'École Polytechnique Fédérale de Lausanne',
 'EPFL',
 'Fonds De La Recherche Scientifique - FNRS',
 'FNRS',
 'Eidgenössische Technische Hochschule Zürich',
 'ETH',
 'nan',
 'Excellent Talent Team of Hainan Province',
 '(QRCBT202121)',
 'Hainan Province Clinical Medical Center',
 '(QWYH202175)',
 'National Natural Science Foundation of China',
 'NSFC',
 '(31960170',
 '82060260)',
 'National Natural Science Foundation of China',
 'NSFC',
 'Hainan Medical University',
 'HMU',
 '(2021NHCTDCKFKT22014',
 'HYYB2021A07',
 'Qhys2021-355',
 'Qhys2021-357)',
 'Hainan Medical University',
 'HMU',
 'Hainan Provincial Department of Science and Technology',
 '(ZDYF2020216)',
 'Hainan Provincial Department of Science and Technology',
 'nan',
 'Alberta Innovates LevMax program',
 '(222300868)',
 'NYU Langone Medical Center',
 'NYULMC',
 'Central South University',
 'CSU',
 '(2020JGA011)',
 'Central South University',
 'CSU',
 'Guangxi Key Laboratory of Multi-Source Information Mining and Security',
 '(MIMS20-08)',
 'Guangxi Key Laboratory of Multi-Source Information Mining and Security',
 'Türkiye Bilimsel ve Teknolojik Araştırma Kurumu',
 'TÜBİTAK',
 'National Science Foundation',
 'NSF',
 '(BCS-1945230',
 'IIS-2114644)',
 'National Science Foundation',
 'NSF',
 'National Institutes of Health',
 'NIH',
 '(R01MH129426)',
 'National Institutes of Health',
 'NIH',
 'Air Force Office of Scientific Research',
 'AFOSR',
 '(FA9550-21-1-0088)',
 'Air Force Office of Scientific Research',
 'AFOSR',
 'Dana Foundation',
 'DF',
 'Physiotherapy Foundation of Canada',
 'PFC',
 'Fundamental Research Funds for the Central Universities',
 '(N180719020',
 'N2019006)',
 'Fundamental Research Funds for the Central Universities',
 'Faculty of Computer Science and Engineering',
 'Key Open Project of Key Laboratory of Data Science and Intelligence Education',
 'Medical Humanities and Social Sciences Project of Hunan Normal University',
 'and Innovation & Entrepreneurship Training Program of Hunan Xiangjiang Artificial Intelligence Academy',
 'National Natural Science Foundation of China',
 'NSFC',
 '(62072173)',
 'National Natural Science Foundation of China',
 'NSFC',
 "Ministry of Education of the People's Republic of China",
 'MOE',
 '(DSIE202101)',
 "Ministry of Education of the People's Republic of China",
 'MOE',
 'Hainan Normal University',
 'HNU',
 'Natural Science Foundation of\xa0Hunan Province',
 '(2020JJ4432)',
 'Natural Science Foundation of\xa0Hunan Province',
 'Education Department of Henan Province',
 '(20A296)',
 'Education Department of Henan Province',
 'National Key Research and Development Program of China',
 'NKRDPC',
 '(2020YFB2104400)',
 'National Key Research and Development Program of China',
 'NKRDPC',
 'Science and Technology Program of Hunan Province',
 '(2018TP1018)',
 'Science and Technology Program of Hunan Province',
 'SENY',
 'National Institutes of Health',
 'NIH',
 '(R01MH112070',
 'R01MH123550)',
 'National Institutes of Health',
 'NIH',
 'BrightFocus Foundation',
 'BFF',
 'National Natural Science Foundation of China',
 'NSFC',
 'Federación Española de Enfermedades Raras',
 'FEDER',
 'Ministerio de Economía y Competitividad',
 'MINECO',
 'Instituto de Salud Carlos III',
 'ISCIII',
 'European Regional Development Fund',
 'ERDF',
 'Fundación Marqués de Valdecilla',
 'FMV',
 'Fonds de Recherche du Québec - Santé',
 'FRQS',
 'National Human Genome Research Institute',
 'NHGRI',
 'Azrieli Center for Autism Research',
 'Azrieli Future Leaders',
 'British Academy',
 'National Institute of Neurological Disorders and Stroke',
 'NINDS',
 'ACAR-TACC',
 'Autism Research Trust',
 'National Institutes of Health',
 'NIH',

In [10]:
from collections import Counter
ranking = Counter(split_comma).most_common(30)
ranking

[('National Natural Science Foundation of China', 78),
 ('NSFC', 73),
 ('nan', 49),
 ('National Key Research and Development Program of China', 20),
 ('NKRDPC', 20),
 ('Fundamental Research Funds for the Central Universities', 16),
 ('National Institutes of Health', 11),
 ('NIH', 11),
 ('National Institute of Mental Health', 11),
 ('NIMH', 11),
 ('Natural Science Foundation of Shandong Province', 10),
 ('NSF', 9),
 ('National Research Foundation of Korea', 8),
 ('NRF', 8),
 ('China Postdoctoral Science Foundation', 8),
 ('National Science Foundation', 7),
 ('Sichuan Province Science and Technology Support Program', 7),
 ('University of Electronic Science and Technology of China', 6),
 ('UESTC', 6),
 ('Japan Society for the Promotion of Science', 5),
 ('Science and Engineering Research Board', 5),
 ('SERB', 5),
 ('Department of Science and Technology', 5),
 ('Ministry of Science and Technology', 5),
 ('India', 5),
 ('NNSF', 5),
 ('NNSFC', 4),
 ('Ministry of Science', 4),
 ('ICT and Future Planning', 4),
 ('MSIP', 4)]

# Country

In [11]:
countries_per_paper = []

for _, row in table_disease.iterrows():

  affiliation_list = (str(row["Affiliations"])).split("; ")
  countries_per_affiliation = []

  for institution in affiliation_list:

    country_name = (institution.split(", "))[-1]
    countries_per_affiliation.append(country_name)

  countries_per_affiliation = list(set(countries_per_affiliation))
  countries_per_paper = countries_per_paper + countries_per_affiliation

countries_per_paper

['United Kingdom',
 'China',
 'China',
 'Mexico',
 'India',
 'Pakistan',
 'United States',
 'United States',
 'Turkey',
 'Singapore',
 'China',
 'China',
 'South Korea',
 'China',
 'China',
 'China',
 'India',
 'China',
 'India',
 'Kuwait',
 'United Kingdom',
 'Malaysia',
 'India',
 'India',
 'India',
 'Iran',
 'Denmark',
 'Canada',
 'United States',
 'Iran',
 'China',
 'China',
 'Pakistan',
 'Saudi Arabia',
 'China',
 'Germany',
 'Canada',
 'South Korea',
 'United States',
 'India',
 'India',
 'Canada',
 'China',
 'United Kingdom',
 'China',
 'Saudi Arabia',
 'Japan',
 'Australia',
 'Canada',
 'China',
 'United States',
 'India',
 'India',
 'China',
 'India',
 'China',
 'China',
 'China',
 'China',
 'China',
 'Pakistan',
 'Saudi Arabia',
 'Italy',
 'China',
 'China',
 'China',
 'China',
 'United States',
 'China',
 'India',
 'China',
 'India',
 'China',
 'India',
 'China',
 'Sri Lanka',
 'India',
 'Bolivia',
 'Spain',
 'Saudi Arabia',
 'China',
 'United States',
 'China',
 'United Kingdom',
 'China',
 'India',
 'India',
 'South Korea',
 'China',
 'India',
 'Italy',
 'France',
 'Ireland',
 'China',
 'Australia',
 'Bangladesh',
 'Bangladesh',
 'China',
 'United States',
 'Sweden',
 'China',
 'Italy',
 'China',
 'Canada',
 'China',
 'China',
 'Canada',
 'Spain',
 'China',
 'China',
 'India',
 'Switzerland',
 'Belgium',
 'Viet Nam',
 'China',
 'China',
 'United Kingdom',
 'Canada',
 'China',
 'United States',
 'United States',
 'Turkey',
 'United States',
 'China',
 'United States',
 'North Macedonia',
 'China',
 'China',
 'Australia',
 'Brazil',
 'United Kingdom',
 'Germany',
 'Spain',
 'United States',
 'Netherlands',
 'Italy',
 'Singapore',
 'Canada',
 'South Korea',
 'United Kingdom',
 'Germany',
 'United States',
 'China',
 'China',
 'Estonia',
 'China',
 'Canada',
 'Netherlands',
 'China',
 'United States',
 'China',
 'China',
 'Egypt',
 'China',
 'China',
 'China',
 'China',
 'China',
 'China',
 'India',
 'United Kingdom',
 'Canada',
 'China',
 'Sri Lanka',
 'China',
 'United States',
 'China',
 'Norway',
 'China',
 'Philippines',
 'China',
 'India',
 'China',
 'Norway',
 'China',
 'Hong Kong',
 'Japan',
 'China',
 'Japan',
 'United Kingdom',
 'United States',
 'United States',
 'Turkey',
 'United Kingdom',
 'China',
 'Canada',
 'Canada',
 'Finland',
 'Spain',
 'China',
 'Canada',
 'United Arab Emirates',
 'United States',
 'Italy',
 'Japan',
 'Brazil',
 'United States',
 'Singapore',
 'United States',
 'China',
 'China',
 'Iran',
 'China',
 'United States',
 'Japan',
 'Singapore',
 'Iran',
 'Canada',
 'Spain',
 'India',
 'China',
 'United States',
 'United States',
 'United States',
 'China',
 'Italy',
 'United States',
 'Canada',
 'United States',
 'China',
 'United States',
 'Iran',
 'Switzerland',
 'India',
 'Netherlands',
 'India',
 'China',
 'South Korea',
 'Italy',
 'Iran',
 'China',
 'Canada',
 'United States',
 'Canada']

In [12]:
from collections import Counter
ranking = Counter(countries_per_paper).most_common(10)
ranking

[('China', 76),
 ('United States', 29),
 ('India', 24),
 ('Canada', 17),
 ('United Kingdom', 10),
 ('Italy', 7),
 ('Iran', 6),
 ('South Korea', 5),
 ('Japan', 5),
 ('Spain', 5)]

In [13]:
full_list = Counter(countries_per_paper)
full_list

Counter({'United Kingdom': 10,
         'China': 76,
         'Mexico': 1,
         'India': 24,
         'Pakistan': 3,
         'United States': 29,
         'Turkey': 3,
         'Singapore': 4,
         'South Korea': 5,
         'Kuwait': 1,
         'Malaysia': 1,
         'Iran': 6,
         'Denmark': 1,
         'Canada': 17,
         'Saudi Arabia': 4,
         'Germany': 3,
         'Japan': 5,
         'Australia': 3,
         'Italy': 7,
         'Sri Lanka': 2,
         'Bolivia': 1,
         'Spain': 5,
         'France': 1,
         'Ireland': 1,
         'Bangladesh': 2,
         'Sweden': 1,
         'Switzerland': 2,
         'Belgium': 1,
         'Viet Nam': 1,
         'North Macedonia': 1,
         'Brazil': 2,
         'Netherlands': 3,
         'Estonia': 1,
         'Egypt': 1,
         'Norway': 2,
         'Philippines': 1,
         'Hong Kong': 1,
         'Finland': 1,
         'United Arab Emirates': 1})